[package]
name = "roco"
version = "0.5.4"
authors = ["Manfred Wallner <schusterfredl@mwallner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocolatey-lib = { path = "../rocolatey-lib" }
#clap = "2.33.3"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
tokio = { version = "1.8.1", features = ["full"] }
